package ImiTrade.portfolio.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;

/**
 * Aggregated {@code portfolio_positions} entity — the current holding of a
 * single stock for a user. Derived from {@link ImiTrade.transaction.domain.Transaction}
 * rows: each buy increases {@code quantity} (recomputing {@code averagePrice}),
 * each sell decreases it, and the row is deleted when {@code quantity} reaches 0.
 *
 * <p>Mapping follows the existing Flyway {@code V1__init_schema.sql} schema exactly:
 * <ul>
 *   <li>{@code id}            — BIGINT PK, generated by default as identity</li>
 *   <li>{@code user_id}       — BIGINT, references {@code users(id)}</li>
 *   <li>{@code stock_id}      — BIGINT, references {@code stocks(id)}</li>
 *   <li>{@code quantity}      — INTEGER, {@code > 0}</li>
 *   <li>{@code average_price} — NUMERIC(19,4)</li>
 * </ul>
 *
 * <p>References to the user and stock are stored as scalar ids (no JPA
 * relationships), matching the rest of the codebase.
 */
@Getter
@Setter
@Entity
@Table(name = "portfolio_positions")
@Builder
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor(access = AccessLevel.PRIVATE)
public class PortfolioPosition {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "user_id", nullable = false)
    private Long userId;

    @Column(name = "stock_id", nullable = false)
    private Long stockId;

    @Column(name = "quantity", nullable = false)
    private Integer quantity;

    @Column(name = "average_price", nullable = false, precision = 19, scale = 4)
    private BigDecimal averagePrice;
}
