package ImiTrade.stocks.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;

/**
 * Persistent {@code stocks} entity.
 *
 * <p>Mapping follows the existing Flyway {@code V1__init_schema.sql} schema exactly
 * (no schema changes are allowed):
 * <ul>
 *   <li>{@code id}            — BIGINT PK, generated by default as identity</li>
 *   <li>{@code ticker}        — VARCHAR(20), unique</li>
 *   <li>{@code company_name}  — VARCHAR(255)</li>
 *   <li>{@code exchange}      — VARCHAR(50)</li>
 *   <li>{@code current_price} — NUMERIC(19,4), added by {@code V3__add_current_price_to_stocks.sql}</li>
 *   <li>{@code lot_size}      — INTEGER, added by {@code V6__add_lot_size_to_stocks.sql}</li>
 * </ul>
 *
 * <p>Stocks are read-only: they are seeded by the {@code V2__insert_initial_stocks.sql}
 * migration and never created/updated/deleted through the API. The only mutable columns
 * are {@code current_price} and {@code lot_size}, both refreshed by the market-data
 * scheduler ({@code MarketDataScheduler}).
 */
@Getter
@Setter
@Entity
@Table(name = "stocks")
@Builder
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor(access = AccessLevel.PRIVATE)
public class Stock {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "ticker", nullable = false, unique = true, length = 20)
    private String ticker;

    @Column(name = "company_name", nullable = false, length = 255)
    private String companyName;

    @Column(name = "exchange", nullable = false, length = 50)
    private String exchange;

    @Column(name = "current_price", nullable = false, precision = 19, scale = 4)
    private BigDecimal currentPrice;

    @Column(name = "lot_size", nullable = false)
    private Integer lotSize;
}
