package ImiTrade.user.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Persistent {@code users} entity.
 *
 * <p>Mapping follows the existing Flyway {@code V1__init_schema.sql} schema exactly
 * (no schema changes are allowed):
 * <ul>
 *   <li>{@code id}            — BIGINT PK, generated by default as identity</li>
 *   <li>{@code email}         — VARCHAR(255), unique</li>
 *   <li>{@code username}      — VARCHAR(100), unique</li>
 *   <li>{@code password_hash} — VARCHAR(255), stores a BCrypt hash</li>
 *   <li>{@code balance}       — NUMERIC(19,4), initial value = 500000.00</li>
 *   <li>{@code created_at}    — TIMESTAMPTZ, defaults to now()</li>
 * </ul>
 */
@Getter
@Setter
@Entity
@Table(name = "users")
@Builder
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor(access = AccessLevel.PRIVATE)
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "email", nullable = false, unique = true, length = 255)
    private String email;

    @Column(name = "username", nullable = false, unique = true, length = 100)
    private String username;

    /** BCrypt password hash; never stores a raw password. */
    @Column(name = "password_hash", nullable = false, length = 255)
    private String passwordHash;

    @Column(name = "balance", nullable = false, precision = 19, scale = 4)
    private BigDecimal balance;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;
}
