package ImiTrade.user.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

/**
 * Persistent {@code users} entity.
 *
 * <p>Supports both registered users and guests:
 * <ul>
 *   <li>{@code id}            — BIGINT PK, generated by default as identity</li>
 *   <li>{@code email}         — VARCHAR(255), unique, nullable for guests</li>
 *   <li>{@code username}      — VARCHAR(100), unique, nullable for guests</li>
 *   <li>{@code password_hash} — VARCHAR(255), nullable for guests</li>
 *   <li>{@code balance}       — NUMERIC(19,4)</li>
 *   <li>{@code is_guest}      — BOOLEAN, default false</li>
 *   <li>{@code guest_token}   — UUID, unique, nullable</li>
 *   <li>{@code created_at}    — TIMESTAMPTZ, defaults to now()</li>
 * </ul>
 */
@Getter
@Setter
@Entity
@Table(name = "users")
@Builder
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor(access = AccessLevel.PRIVATE)
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "email", unique = true, length = 255)
    private String email;

    @Column(name = "username", unique = true, length = 100)
    private String username;

    /** BCrypt password hash; never stores a raw password. Nullable for guests. */
    @Column(name = "password_hash", length = 255)
    private String passwordHash;

    @Column(name = "balance", nullable = false, precision = 19, scale = 4)
    private BigDecimal balance;

    @Column(name = "is_guest", nullable = false)
    @Builder.Default
    private Boolean isGuest = false;

    @Column(name = "guest_token", unique = true)
    private UUID guestToken;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;
}
