-- H2 (PostgreSQL compatibility mode) schema for integration tests.
-- Mirrors the production Flyway V1 migration (only the tables used in tests).
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    email         VARCHAR(255),
    username      VARCHAR(100),
    password_hash VARCHAR(255),
    balance       NUMERIC(19,4) NOT NULL,
    is_guest      BOOLEAN      NOT NULL DEFAULT false,
    guest_token   UUID         UNIQUE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email    UNIQUE (email),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT ck_users_balance_non_negative CHECK (balance >= 0)
);

CREATE TABLE IF NOT EXISTS stocks (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    ticker        VARCHAR(20)  NOT NULL,
    company_name  VARCHAR(255) NOT NULL,
    exchange      VARCHAR(50)  NOT NULL,
    current_price NUMERIC(19,4) NOT NULL,
    lot_size      INTEGER      NOT NULL,
    CONSTRAINT pk_stocks PRIMARY KEY (id),
    CONSTRAINT uk_stocks_ticker UNIQUE (ticker)
);

CREATE TABLE IF NOT EXISTS portfolio_positions (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT       NOT NULL,
    stock_id      BIGINT       NOT NULL,
    quantity      INTEGER      NOT NULL,
    average_price NUMERIC(19,4) NOT NULL,
    CONSTRAINT pk_portfolio_positions PRIMARY KEY (id),
    CONSTRAINT uk_portfolio_positions_user_stock UNIQUE (user_id, stock_id),
    CONSTRAINT ck_portfolio_positions_quantity_positive CHECK (quantity > 0),
    CONSTRAINT fk_portfolio_positions_users
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_portfolio_positions_stocks
        FOREIGN KEY (stock_id) REFERENCES stocks (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS transactions (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    user_id      BIGINT       NOT NULL,
    stock_id     BIGINT       NOT NULL,
    type         VARCHAR(10)  NOT NULL,
    quantity     INTEGER      NOT NULL,
    price        NUMERIC(19,4) NOT NULL,
    total_amount NUMERIC(19,4) NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_transactions PRIMARY KEY (id),
    CONSTRAINT ck_transactions_quantity_positive CHECK (quantity > 0),
    CONSTRAINT fk_transactions_users
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_transactions_stocks
        FOREIGN KEY (stock_id) REFERENCES stocks (id) ON DELETE RESTRICT
);
