-- ============================================================
-- ImiTrade — initial schema
-- 4 tables: users, stocks, portfolio_positions, transactions
-- ============================================================

-- ---- ENUM for transaction type ---------------------------------------------
CREATE TYPE transaction_type AS ENUM ('BUY', 'SELL');

-- ---- users ------------------------------------------------------------------
CREATE TABLE users (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    email         VARCHAR(255) NOT NULL,
    username      VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    balance       NUMERIC(19,4) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email    UNIQUE (email),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT ck_users_balance_non_negative CHECK (balance >= 0)
);

-- ---- stocks -----------------------------------------------------------------
CREATE TABLE stocks (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    ticker       VARCHAR(20)  NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    exchange     VARCHAR(50)  NOT NULL,
    CONSTRAINT pk_stocks PRIMARY KEY (id),
    CONSTRAINT uk_stocks_ticker UNIQUE (ticker)
);

-- ---- portfolio_positions ----------------------------------------------------
CREATE TABLE portfolio_positions (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT       NOT NULL,
    stock_id      BIGINT       NOT NULL,
    quantity      INTEGER      NOT NULL,
    average_price NUMERIC(19,4) NOT NULL,
    CONSTRAINT pk_portfolio_positions PRIMARY KEY (id),
    CONSTRAINT uk_portfolio_positions_user_stock UNIQUE (user_id, stock_id),
    CONSTRAINT ck_portfolio_positions_quantity_positive CHECK (quantity > 0),
    CONSTRAINT fk_portfolio_positions_users
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_portfolio_positions_stocks
        FOREIGN KEY (stock_id) REFERENCES stocks (id) ON DELETE RESTRICT
);

CREATE INDEX ix_portfolio_positions_user_id
    ON portfolio_positions (user_id);

-- ---- transactions -----------------------------------------------------------
CREATE TABLE transactions (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    user_id      BIGINT       NOT NULL,
    stock_id     BIGINT       NOT NULL,
    type         transaction_type NOT NULL,
    quantity     INTEGER      NOT NULL,
    price        NUMERIC(19,4) NOT NULL,
    total_amount NUMERIC(19,4) NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_transactions PRIMARY KEY (id),
    CONSTRAINT ck_transactions_quantity_positive CHECK (quantity > 0),
    CONSTRAINT fk_transactions_users
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_transactions_stocks
        FOREIGN KEY (stock_id) REFERENCES stocks (id) ON DELETE RESTRICT
);

CREATE INDEX ix_transactions_user_created
    ON transactions (user_id, created_at DESC);
