package ImiTrade.transaction.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Immutable {@code transactions} entity — the source of truth for every buy/sell
 * operation. One row is appended per trade and never updated.
 *
 * <p>Mapping follows the existing Flyway {@code V1__init_schema.sql} schema exactly:
 * <ul>
 *   <li>{@code id}           — BIGINT PK, generated by default as identity</li>
 *   <li>{@code user_id}      — BIGINT, references {@code users(id)}</li>
 *   <li>{@code stock_id}     — BIGINT, references {@code stocks(id)}</li>
 *   <li>{@code type}         — {@code transaction_type} enum ('BUY'/'SELL')</li>
 *   <li>{@code quantity}     — INTEGER, {@code > 0}</li>
 *   <li>{@code price}        — NUMERIC(19,4)</li>
 *   <li>{@code total_amount} — NUMERIC(19,4)</li>
 *   <li>{@code created_at}   — TIMESTAMPTZ, defaults to {@code now()}</li>
 * </ul>
 *
 * <p>References to the user and stock are stored as scalar ids (no JPA
 * relationships), matching the rest of the codebase where entities are not
 * wired together with associations.
 */
@Getter
@Setter
@Entity
@Table(name = "transactions")
@Builder
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor(access = AccessLevel.PRIVATE)
public class Transaction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "user_id", nullable = false)
    private Long userId;

    @Column(name = "stock_id", nullable = false)
    private Long stockId;

    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "type", nullable = false, length = 10)
    private TransactionType type;

    @Column(name = "quantity", nullable = false)
    private Integer quantity;

    @Column(name = "price", nullable = false, precision = 19, scale = 4)
    private BigDecimal price;

    @Column(name = "total_amount", nullable = false, precision = 19, scale = 4)
    private BigDecimal totalAmount;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;
}
